### PR TITLE
Feature/801 add license scan to ci

### PR DESCRIPTION
**Pull request by lewisdaly**
Part of: mojaloop/project#801

Adds 2 new steps to the ci process:
- `vunerability-check`: uses npm audit to check for and resolve vulnerabilities in packages
- `audit-license`: checks for disallowed or unknown licenses using the license-scanner tool

In addition:
- updated standard and ran `standard --fix` across the project

### CODE REVIEW

**Comment by rmothilal** [comment]
Hey @lewisdaly, the integration tests are failing

**Review by rmothilal — CHANGES_REQUESTED** [review]
integration tests are failing. The seemed to pass in the PR prior to this I think.

**Comment by lewisdaly** [comment]
@rmothilal yeah it's because the database is still postgres, but the version of the database library we updated to (5.2.1) only supports MySQL now.

I'll downgrade the database library for now.

**Review by rmothilal — APPROVED** [review]
happy

**Pull request merged**
